// Generated by config.py from config.json
#pragma once

typedef uint32_t cmd_arg_int; // Numbers given as argumenets use this type

#define FILE_PACKET_SIZE 64 
#define COMMAND_CHARS 2
#define MAX_ARGS 1
#define COMMAND_LEN 6 
#define ACK_TIMEOUT_MS 5 /* Resend un-acknowledged command after this time */

#define ANIMATION_META_LEN 6 /* How many metadata numbers are in the animation file */
#define ROUND_DIV(num, nearest) ((num + (nearest - 1)) / nearest) 
#define CIEL_INT(num, nearest) (ROUND_DIV(num, nearest) * nearest)

// For column major byte alligned framebuffer / bitmaps
#define CALC_BMP_BYTES(width, height) (width * ROUND_DIV(height, 8))

#define START_FILE_TRANSFER "ST"
#define REQUEST_NEXT_PACKET "RP"
#define ACKNOWLEDGE "AK"
#define REQUEST_TIME "RT"
#define SEND_ERASE_PROGRESS "EP"
#define SEND_HOUR "SH"
#define SEND_MINUTE "Sm"
#define SEND_SECOND "SS"
#define SEND_SUBSECOND "Ss"
#define SET_TIME "TS"
#define SEND_WEEKDAY "Sd"
#define SEND_DAY "SD"
#define SEND_MONTH "SM"
#define SEND_YEAR "SY"
#define SET_DATE "DS"
#define CAL_RTC_FORWARD "CF"
#define CAL_RTC_BACKWARD "CB"
#define ERROR_COMMAND "er"
