// Generated by config.py from config.json
#pragma once

typedef uint16_t cmd_arg_int; // Numbers given as argumenets use this type

#define FRAME_PACKET_SIZE 64 /* Frame buffer packets can be this long or shorter*/
#define COMMAND_CHARS 2
#define MAX_ARGS 2
#define COMMAND_LEN 6 
#define ACK_TIMEOUT_MS 5 /* Resend un-acknowledged command after this time */

#define ROUND_DIV(num, nearest) ((num + (nearest - 1)) / nearest) 
#define CIEL_INT(num, nearest) (ROUND_DIV(num, nearest) * nearest)

// For column major byte alligned framebuffer / bitmaps
#define CALC_FB_BYTES(width, height) (width * ROUND_DIV(height, 8))
#define PACKET_ALIGNED_FB_SIZE(width, height) CIEL_INT(CALC_FB_BYTES(width, height), FRAME_PACKET_SIZE)

#define ANIMATION_REQUEST "AR"
#define SET_FRAMERATE "SF"
#define SET_LOCATION "SL"
#define START_ANIMATION "SA"
#define SET_ORIENTATION "SO"
#define FRAME_REQUEST "FR"
#define NEXT_FRAME_PACKET "NP"
#define CANCEL_ANIMATION "CA"
#define ACKNOWLEDGE "AK"
#define ERROR_COMMAND "er"
