"""
    This module is responsible for reading config information from the json,
    and converting it into a c header file for the embedded software
"""

import json

output_header = "../usb_cmd_cfg.h"
config_json = "config.json"

class Config:
    def __init__(self):
        with open(config_json) as json_file:
            json_data = json.load(json_file)
            self.num_byte_len = int(json_data["config"]["num_byte_len"])
            self.message_chars = int(json_data["config"]["message_chars"])
            self.max_arguments = int(json_data["config"]["message_chars"])
            self.packet_size = int(json_data["config"]["packet_size"])
            self.ack_timout_ms = int(json_data["config"]["ack_timout_ms"])

            self.bmp_row_major = json_data["config"]["bmp_row_major"].lower() == "true" 
            self.bmp_lsb_first = json_data["config"]["bmp_lsb_first"].lower() == "true" 

            self.commands_dict = json_data["commands"]

    def generate_header(self):
        num_type = "uint8_t"
        match self.num_byte_len:
            case 1:
                num_type = "uint8_t"
            case 2:
                num_type = "uint16_t"
            case 4:
                num_type = "uint32_t"
            case 8:
                num_type = "uint64_t"
            case _:
                raise Exception("Number byte length must be 1, 2, 4, or 8")

        header_content = f"""// Generated by config.py from {config_json}
            #pragma once

            typedef {num_type} cmd_arg_int; // Numbers given as argumenets use this type

            #define FRAME_PACKET_SIZE {self.packet_size} /* Frame buffer packets can be this long or shorter*/
            #define COMMAND_CHARS {self.message_chars}
            #define MAX_ARGS {self.max_arguments}
            #define COMMAND_LEN {self.message_chars + (self.num_byte_len * self.max_arguments)} 
            #define ACK_TIMEOUT_MS {self.ack_timout_ms} /* Resend un-acknowledged command after this time */

            #define ROUND_DIV(num, nearest) ((num + (nearest - 1)) / nearest) 
            #define CIEL_INT(num, nearest) (ROUND_DIV(num, nearest) * nearest)
        """


        with open(output_header, "w") as f:
            lines = (line.lstrip() for line in header_content.splitlines())
            f.write("\n".join(lines))
            f.write("\n")

            if (self.bmp_row_major):
                f.write("// For row major byte alligned framebuffer / bitmaps\n")
                f.write("#define CALC_FB_BYTES(width, height) (ROUND_DIV(width, 8) * height)\n")
            else:
                f.write("// For column major byte alligned framebuffer / bitmaps\n")
                f.write("#define CALC_FB_BYTES(width, height) (width * ROUND_DIV(height, 8))\n")

            f.write("#define PACKET_ALIGNED_FB_SIZE(width, height) CIEL_INT(CALC_FB_BYTES(width, height), FRAME_PACKET_SIZE)\n\n")

            for command, command_id in self.commands_dict.items():
                f.write(f"#define {command.upper()} \"{command_id}\"\n")

# For testing
if __name__ == '__main__':
    config = Config()
    config.generate_header()
